### ISSUE TITLE
missing css classes?

### ISSUE THREAD

**Issue by maxgurewitz** [fedragon/elm-typed-dropdown#1]
Hello! 

It looks like your dropdown.css file is missing the `dropdown open` class and others.  Are you importing them from an external library?  It'd be great if this information could be included in the readme!

**Comment by fedragon** [comment]
Hi @maxgurewitz, good point! I am indeed not providing all classes by default and using Bootstrap 3.3.7 in the example... I just mentioned it in the README!

ps: I cannot update the example to 0.19 right now because of https://github.com/massung/elm-css/issues/4 but I will do it as soon as the dependency issue is fixed.
